name: Paint_Battle
version: '1.0-SNAPSHOT'
main: net.mochinekoserver.paint_battle.Main
api-version: '1.20'

commands:
  game_start:
    description: ゲームを開始するコマンド
    permission: paintbattle.game_start
  game_stop:
    description: ゲームを停止するコマンド
    permission: paintbattle.game_stop
  game_team:
    description: チームに関するコマンド
    permission: paintbattle.game_team
  kit_select:
    description: キットを選択するコマンド
    permission: paintbattle.kit_select